language: node_js
services:
 - postgresgl
node_js:

 - stable
before_script:

 - psql -c 'create database <database-name>;' -U postgres
 - npm run db:migrate

script:
 - npm run test

after_success:
- npm run coverage