language: node_js
services:
 - postgresgl
node_js:

 - stable
before_script:

 - psql -c 'create database postgres WITH PASSWORD "12345" ;' -U postgres

script:
 - npm run test

after_success:
- npm run coverage